name: Compile with Nuitka

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.9'

      - name: Install Nuitka
        run: |
          python -m pip install --upgrade pip
          pip install nuitka

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Compile with Nuitka
        run: |
          nuitka --onefile --windows-disable-console --windows-icon-from-ico="resources/icon.ico" --include-data-dir=resources=resources main.py
        env:
          PYTHONPATH: ${{ github.workspace }}

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: compiled-executable
          path: |
            Minecraft_Mod_Translate_too/mcmt.exe
